USE [master]
GO

/****** Object:  Database [Recuperacao]    Script Date: 04/17/2018 22:30:17 ******/
CREATE DATABASE [Recuperacao] ON  PRIMARY 
( NAME = N'Recuperacao', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Recuperacao.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Recuperacao_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Recuperacao_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Recuperacao] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Recuperacao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Recuperacao] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Recuperacao] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Recuperacao] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Recuperacao] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Recuperacao] SET ARITHABORT OFF 
GO

ALTER DATABASE [Recuperacao] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Recuperacao] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Recuperacao] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Recuperacao] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Recuperacao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Recuperacao] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Recuperacao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Recuperacao] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Recuperacao] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Recuperacao] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Recuperacao] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Recuperacao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Recuperacao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Recuperacao] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Recuperacao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Recuperacao] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Recuperacao] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Recuperacao] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Recuperacao] SET  READ_WRITE 
GO

ALTER DATABASE [Recuperacao] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Recuperacao] SET  MULTI_USER 
GO

ALTER DATABASE [Recuperacao] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Recuperacao] SET DB_CHAINING OFF 
GO


